version: "3.6"

services:
  trentvineyard-php:
    image: elliotjreed/trentvineyard-php
    container_name: trentvineyard-php
    restart: always
    networks:
      - trentvineyard
    volumes:
      - ./invitations.sqlite3:/var/www/html/invitations.sqlite3:rw

  trentvineyard-api-nginx:
    image: elliotjreed/trentvineyard-api-nginx
    container_name: trentvineyard-api-nginx
    restart: always
    networks:
      - trentvineyard
      - web
    depends_on:
      - trentvineyard-php
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:trentvineyard-api.elliotjreed.com"
      - "traefik.protocol=h2c"
      - "traefik.port=85"

  trentvineyard-nginx:
    image: elliotjreed/trentvineyard-nginx
    container_name: trentvineyard-nginx
    restart: always
    networks:
      - trentvineyard
      - web
    depends_on:
      - trentvineyard-php
      - trentvineyard-api-nginx
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:invite.trentv.org"
      - "traefik.protocol=h2c"
      - "traefik.port=84"

networks:
  web:
    external: true
  trentvineyard:
    name: trentvineyard

